apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-small-production
  namespace: istio-system-tracing
spec:
  strategy: production
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: true                                 // turn the cron job deployment on and off
      numberOfDays: 7                               // number of days to wait before deleting a record
      schedule: "55 23 * * *"                       // cron expression for it to run    
    elasticsearch:
      nodeCount: 1
      storage: 
        size: 1Gi
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
        limits:
          memory: 1Gi
      redundancyPolicy: ZeroRedundancy  
