kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: hello-remote
spec:
  host: hello.remote.com
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  port:
    targetPort: http2
  wildcardPolicy: None
