apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-hello-traced-quarkus-service
  annotations:
    "sidecar.jaegertracing.io/inject": "jaeger-production"
spec:
  selector:
    matchLabels:
      app: deployment-hello-traced-quarkus-service
  template:
    metadata:
      labels:
        app: deployment-hello-traced-quarkus-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: hello-traced-quarkus-service
        image: quay.io/skoussou/quarkus-opentracing:v1.1.0
        env:
          - name: hello-service-url
            value: 'http://deployment-hello-traced-quarkus-service:8080'
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http-hello
        command:
          - java
        imagePullPolicy: IfNotPresent
        terminationMessagePolicy: File
        args:
          - '-jar'
          - /deployments/quarkus-run.jar
          - '-cp'
          - >-
            /deployments/lib/io.quarkus.quarkus-security-runtime-spi-1.12.0.Final.jar:/deployments/lib/io.quarkus.quarkus-vertx-http-dev-console-runtime-spi-1.12.0.Final.jar:/deployments/lib/io.smallrye.reactive.mutiny-0.13.0.jar:/deployments/lib/io.quarkus.security.quarkus-security-1.1.3.Final.jar:/deployments/lib/io.netty.netty-codec-4.1.49.Final.jar:/deployments/lib/io.netty.netty-handler-4.1.49.Final.jar:/deployments/lib/io.quarkus.quarkus-netty-1.12.0.Final.jar:/deployments/lib/io.netty.netty-common-4.1.49.Final.jar:/deployments/lib/io.netty.netty-buffer-4.1.49.Final.jar:/deployments/lib/io.netty.netty-transport-4.1.49.Final.jar:/deployments/lib/io.netty.netty-codec-socks-4.1.49.Final.jar:/deployments/lib/io.netty.netty-handler-proxy-4.1.49.Final.jar:/deployments/lib/io.netty.netty-codec-http-4.1.49.Final.jar:/deployments/lib/io.netty.netty-codec-http2-4.1.49.Final.jar:/deployments/lib/io.netty.netty-resolver-4.1.49.Final.jar:/deployments/lib/io.netty.netty-codec-dns-4.1.49.Final.jar:/deployments/lib/io.netty.netty-resolver-dns-4.1.49.Final.jar:/deployments/lib/com.fasterxml.jackson.core.jackson-core-2.12.1.jar:/deployments/lib/io.vertx.vertx-core-3.9.5.jar:/deployments/lib/io.quarkus.quarkus-vertx-core-1.12.0.Final.jar:/deployments/lib/io.vertx.vertx-web-common-3.9.5.jar:/deployments/lib/io.vertx.vertx-auth-common-3.9.5.jar:/deployments/lib/io.vertx.vertx-bridge-common-3.9.5.jar:/deployments/lib/io.vertx.vertx-web-3.9.5.jar:/deployments/lib/io.quarkus.quarkus-vertx-http-1.12.0.Final.jar:/deployments/lib/jakarta.validation.jakarta.validation-api-2.0.2.jar:/deployments/lib/io.quarkus.quarkus-resteasy-server-common-1.12.0.Final.jar:/deployments/lib/io.quarkus.quarkus-resteasy-1.12.0.Final.jar:/deployments/lib/org.eclipse.microprofile.config.microprofile-config-api-1.4.jar:/deployments/lib/org.eclipse.microprofile.opentracing.microprofile-opentracing-api-1.3.3.jar:/deployments/lib/org.eclipse.microprofile.rest.client.microprofile-rest-client-api-1.4.1.jar:/deployments/lib/io.opentracing.opentracing-api-0.31.0.jar:/deployments/lib/io.opentracing.opentracing-noop-0.31.0.jar:/deployments/lib/io.opentracing.contrib.opentracing-web-servlet-filter-0.2.3.jar:/deployments/lib/io.opentracing.contrib.opentracing-concurrent-0.2.0.jar:/deployments/lib/io.opentracing.contrib.opentracing-jaxrs2-0.4.1.jar:/deployments/lib/io.opentracing.contrib.opentracing-tracerresolver-0.1.8.jar:/deployments/lib/io.opentracing.contrib.opentracing-interceptors-0.0.4.jar:/deployments/lib/io.smallrye.smallrye-opentracing-1.3.5.jar:/deployments/lib/org.jboss.spec.javax.ws.rs.jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar:/deployments/lib/io.smallrye.smallrye-fault-tolerance-tracing-propagation-4.3.2.jar:/deployments/lib/jakarta.inject.jakarta.inject-api-1.0.jar:/deployments/lib/jakarta.annotation.jakarta.annotation-api-1.3.5.jar:/deployments/lib/jakarta.el.jakarta.el-api-3.0.3.jar:/deployments/lib/jakarta.enterprise.jakarta.enterprise.cdi-api-2.0.2.jar:/deployments/lib/io.quarkus.quarkus-development-mode-spi-1.12.0.Final.jar:/deployments/lib/io.smallrye.common.smallrye-common-annotation-1.5.0.jar:/deployments/lib/io.smallrye.config.smallrye-config-common-1.10.2.jar:/deployments/lib/io.smallrye.common.smallrye-common-function-1.5.0.jar:/deployments/lib/io.smallrye.common.smallrye-common-expression-1.5.0.jar:/deployments/lib/io.smallrye.common.smallrye-common-constraint-1.5.0.jar:/deployments/lib/io.smallrye.common.smallrye-common-classloader-1.5.0.jar:/deployments/lib/io.smallrye.config.smallrye-config-1.10.2.jar:/deployments/lib/org.jboss.logging.jboss-logging-3.4.1.Final.jar:/deployments/lib/org.jboss.logmanager.jboss-logmanager-embedded-1.0.6.jar:/deployments/lib/org.jboss.logging.jboss-logging-annotations-2.2.0.Final.jar:/deployments/lib/org.jboss.threads.jboss-threads-3.2.0.Final.jar:/deployments/lib/org.slf4j.slf4j-api-1.7.30.jar:/deployments/lib/org.jboss.slf4j.slf4j-jboss-logmanager-1.1.0.Final.jar:/deployments/lib/org.graalvm.sdk.graal-sdk-21.0.0.jar:/deployments/lib/org.wildfly.common.wildfly-common-1.5.4.Final-format-001.jar:/deployments/lib/io.smallrye.common.smallrye-common-io-1.5.0.jar:/deployments/lib/io.quarkus.quarkus-bootstrap-runner-1.12.0.Final.jar:/deployments/lib/io.quarkus.quarkus-core-1.12.0.Final.jar:/deployments/lib/io.opentracing.opentracing-util-0.31.0.jar:/deployments/lib/com.google.code.gson.gson-2.8.6.jar:/deployments/lib/io.jaegertracing.jaeger-core-0.34.3.jar:/deployments/lib/org.apache.thrift.libthrift-0.13.0.jar:/deployments/lib/com.squareup.okio.okio-1.17.2.jar:/deployments/lib/com.squareup.okhttp3.okhttp-3.14.9.jar:/deployments/lib/io.jaegertracing.jaeger-thrift-0.34.3.jar:/deployments/lib/jakarta.activation.jakarta.activation-api-1.2.1.jar:/deployments/lib/io.quarkus.quarkus-jaeger-1.12.0.Final.jar:/deployments/lib/org.glassfish.jakarta.json-1.1.6.jar:/deployments/lib/io.quarkus.quarkus-jsonp-1.12.0.Final.jar:/deployments/lib/jakarta.servlet.jakarta.servlet-api-4.0.3.jar:/deployments/lib/io.quarkus.quarkus-smallrye-opentracing-1.12.0.Final.jar:/deployments/lib/jakarta.transaction.jakarta.transaction-api-1.3.3.jar:/deployments/lib/io.quarkus.arc.arc-1.12.0.Final.jar:/deployments/lib/org.eclipse.microprofile.context-propagation.microprofile-context-propagation-api-1.0.1.jar:/deployments/lib/io.quarkus.quarkus-arc-1.12.0.Final.jar:/deployments/lib/org.jboss.spec.javax.xml.bind.jboss-jaxb-api_2.3_spec-2.0.0.Final.jar:/deployments/lib/org.jboss.resteasy.resteasy-core-spi-4.5.9.Final.jar:/deployments/lib/org.reactivestreams.reactive-streams-1.0.3.jar:/deployments/lib/com.ibm.async.asyncutil-0.1.0.jar:/deployments/lib/org.jboss.resteasy.resteasy-core-4.5.9.Final.jar:/deployments/lib/com.sun.activation.jakarta.activation-1.2.1.jar:/deployments/lib/io.quarkus.quarkus-resteasy-common-1.12.0.Final.jar:/deployments/lib/org.jboss.resteasy.resteasy-client-api-4.5.9.Final.jar:/deployments/lib/commons-codec.commons-codec-1.14.jar:/deployments/lib/commons-io.commons-io-2.8.0.jar:/deployments/lib/org.jboss.resteasy.resteasy-client-4.5.9.Final.jar:/deployments/lib/org.jboss.resteasy.resteasy-client-microprofile-4.5.9.Final.jar:/deployments/lib/jakarta.interceptor.jakarta.interceptor-api-1.2.5.jar:/deployments/lib/org.apache.httpcomponents.httpcore-4.4.14.jar:/deployments/lib/org.apache.httpcomponents.httpcore-nio-4.4.14.jar:/deployments/lib/org.apache.httpcomponents.httpclient-4.5.13.jar:/deployments/lib/org.apache.httpcomponents.httpasyncclient-4.1.4.jar:/deployments/lib/org.jboss.logging.commons-logging-jboss-logging-1.0.0.Final.jar:/deployments/lib/io.quarkus.quarkus-rest-client-1.12.0.Final.jar:/deployments/lib/io.quarkus.quarkus-kubernetes-client-internal-1.12.0.Final.jar:/deployments/lib/io.quarkus.quarkus-openshift-1.12.0.Final.jar
          - '-Dquarkus.http.host=0.0.0.0'
          - '-Djava.util.logging.manager=org.jboss.logmanager.LogManager'
---
kind: Service
apiVersion: v1
metadata:
  name: deployment-hello-traced-quarkus-service
spec:
  ports:
    - name: http-hello
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: deployment-hello-traced-quarkus-service
  type: ClusterIP
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: opentracing-hello
spec:
  hosts:
    - '*'
  gateways:
    - opentracing-hello-gateway
  http:
    - match:
        - uri:
            exact: /chain
        - uri:
            exact: /hello
      route:
        - destination:
            host: deployment-hello-traced-quarkus-service
            port:
              number: 8080
---
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: opentracing-hello-gateway
spec:
  servers:
    - hosts:
        - '*'
      port:
        name: deployment-http-hello-traced-quarkus-service
        number: 80
        protocol: HTTP
  selector:
    istio: ingressgateway              
