apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: <tenant-x>
spec:
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  general:
    logging:
      logAsJSON: true
  policy:
    type: Istiod
  profiles:
    - default
  proxy:
    accessLogging:
      file:
        name: /dev/stdout
    networking:
      trafficControl:
        outbound:
          policy: REGISTRY_ONLY
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger
  version: v2.0  
