apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: <tenant-x>
  namespace: <istio-system-tenant-x>
spec:
  tracing:
    sampling: 10000
    type: Jaeger
  general:
    logging:
      logAsJSON: true
  profiles:
    - default
  proxy:
    accessLogging:
      file:
        name: /dev/stdout
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  security:
    controlPlane:
      mtls: true
    dataPlane:
      mtls: true
  version: v2.1
  telemetry:
    type: Istiod
